// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto_models/db_meta.proto

package proto_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dbname        string                 `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Indexes       []string               `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBase) Reset() {
	*x = DataBase{}
	mi := &file_proto_models_db_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBase) ProtoMessage() {}

func (x *DataBase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_db_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBase.ProtoReflect.Descriptor instead.
func (*DataBase) Descriptor() ([]byte, []int) {
	return file_proto_models_db_meta_proto_rawDescGZIP(), []int{0}
}

func (x *DataBase) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

func (x *DataBase) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DataBase) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DataBase) GetIndexes() []string {
	if x != nil {
		return x.Indexes
	}
	return nil
}

var File_proto_models_db_meta_proto protoreflect.FileDescriptor

const file_proto_models_db_meta_proto_rawDesc = "" +
	"\n" +
	"\x1aproto_models/db_meta.proto\x12\x06models\"z\n" +
	"\bDataBase\x12\x16\n" +
	"\x06dbname\x18\x01 \x01(\tR\x06dbname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aindexes\x18\x04 \x03(\tR\aindexesB\x0fZ\rproto_models/b\x06proto3"

var (
	file_proto_models_db_meta_proto_rawDescOnce sync.Once
	file_proto_models_db_meta_proto_rawDescData []byte
)

func file_proto_models_db_meta_proto_rawDescGZIP() []byte {
	file_proto_models_db_meta_proto_rawDescOnce.Do(func() {
		file_proto_models_db_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_models_db_meta_proto_rawDesc), len(file_proto_models_db_meta_proto_rawDesc)))
	})
	return file_proto_models_db_meta_proto_rawDescData
}

var file_proto_models_db_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_models_db_meta_proto_goTypes = []any{
	(*DataBase)(nil), // 0: models.DataBase
}
var file_proto_models_db_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_models_db_meta_proto_init() }
func file_proto_models_db_meta_proto_init() {
	if File_proto_models_db_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_models_db_meta_proto_rawDesc), len(file_proto_models_db_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_models_db_meta_proto_goTypes,
		DependencyIndexes: file_proto_models_db_meta_proto_depIdxs,
		MessageInfos:      file_proto_models_db_meta_proto_msgTypes,
	}.Build()
	File_proto_models_db_meta_proto = out.File
	file_proto_models_db_meta_proto_goTypes = nil
	file_proto_models_db_meta_proto_depIdxs = nil
}
